### ISSUE TITLE
Localbitcoins wallet is shown as null

### ISSUE THREAD

**Issue by gustakasn0v** [thanksmister/Local-Trader-Android#1] opened 2018-10-18 09:42 UTC
## Environment

- App version: 2.4.5

- Phone: OnePlus 6

- Android version: 9.0

## Steps to reproduce

- Open app

- Go to 'Receive' menu

- Notice it says 'null' under barcode. Clicking it copies the value 'null' into the keyboard

## Additional info

- Tried to refresh app data multiple times, logging out and then back in

**Comment by thanksmister** [comment] 2018-10-18 14:03
Hey, thanks for the feedback.  Did you just create your account?

**Comment by gustakasn0v** [comment] 2018-10-18 21:04
Thanks for the quick reply! I've just started using the app, but I've been using localbitcoins for several months now.

**Comment by thanksmister** [comment] 2018-10-18 21:23
I just tested on a new install for Pixel device and I was able to see the receiving address and QR code in the receiving tab.  I am wondering if you have received any Bitcoin to your account?  There was a bug for new accounts that LocalBitcoins would not show any receiving addresses for new accounts that had a zero balance.   I am a bit stuck because without being able to reproduce the issue, I may not be able to help much.

**Comment by gustakasn0v** [comment] 2018-10-18 22:45
I do see the QR code, but can't copy the bitcoin address
Although you're right, currently my account balance is zero. Most of the times it is, as I only send money to localbitcoins that I'm going to exchange shortly. I'll check again when I have a positive balance on my account

Thanks again for the help!

**Comment by thanksmister** [comment] 2018-10-19 15:48
So what do you see under the wallet tab?  Do you see any transactions?  It could be that for some reason your account isn't syncing locally.

**Comment by gustakasn0v** [comment] 2018-10-22 09:45
I think you may be on to something here. After inspecting all the app's views, I've found the following:

- The dashboard doesn't sync properly. Only the notifications tab syncs, the advertisements and trades tabs don't show my data (although I've made at least one trade recently)

- As discussed, the receive view doesn't sync

- The wallet view does seem to sync, showing my most recent wallet transaction

I've tried deleting all the app's data and signing in again, but that didn't solve the issue. I have 2FA turned on, if it helps

**Comment by thanksmister** [comment] 2018-10-22 12:32
There is a background sync option in the device settings.  Go to your device settings then look for Accounts then find Local Trader then you should have Sync option and make sure it’ on.  Next go to the App permissions and make sure they are on.

**Comment by thanksmister** [comment] 2018-10-22 12:34
You should also be able to do a pull to refresh on the views to force refresh the data.   It sounds as though your device is preventing syncing in the background for the application.

**Comment by gustakasn0v** [comment] 2018-10-25 17:57
Some more observations:

- Account sync for LocalTrader is enabled

- The only app-lever permissions I could find related to Background are under Battery. There's one to restrict battery usage under background (disabled for this app), and another one to enable battery optimizations (defaults to true; I tried disabling it, force stopping the app and relaunching, but the issue persists). Bear in mind the way background works on Android has changed a lot in O (I've been told, I'm not an Android dev unfortunately)

- Manually syncing the views mentioned above doesn't work. I get a spinner and a message saying 'Refreshing data...' but data never syncs

**Comment by thanksmister** [comment] 2018-10-25 18:06
This may be an issue with the data you are receiving.  If you want to test this, you can delete all your advertisements on LBC and create new ones. Sometimes LBC sends bad data with their API and its not possible for the application to catch the issue.  I have no current reports to report such issues either because it would be a privacy issue.   It's worth a try, but so far on my end I am not able to reproduce the issue on any of my devices with my account.   Unfortunately LBC only allows a single account even for developers, so I can't even create other accounts to test.

**Comment by thanksmister** [comment] 2019-03-24 15:48
Fixed in beta version, closing issue pending prodution release

**Closed as completed by thanksmister** 2019-03-24 15:48 UTC
